-- Executar no banco: Portal_Integra (SQL Server)
-- RH - Composição Remuneração (cache local estilo Massey MF_Result)
-- Colunas tipadas alinhadas à view Oracle.

CREATE TABLE dbo.RH_ComposicaoJob (
    SyncId       UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Status       VARCHAR(20)  NOT NULL,
    Step         VARCHAR(40)  NULL,
    Message      NVARCHAR(4000) NULL,
    Progress     INT NOT NULL CONSTRAINT DF_RH_CompJob_Progress DEFAULT (0),
    Total        INT NOT NULL CONSTRAINT DF_RH_CompJob_Total DEFAULT (0),
    Done         INT NOT NULL CONSTRAINT DF_RH_CompJob_Done DEFAULT (0),
    IsActive     BIT NOT NULL CONSTRAINT DF_RH_CompJob_IsActive DEFAULT (0),
    ColumnsJson  NVARCHAR(MAX) NULL,
    WorkerPid    INT NULL,
    Error        NVARCHAR(MAX) NULL,
    StartedAt    DATETIME2(0) NOT NULL,
    UpdatedAt    DATETIME2(0) NOT NULL,
    FinishedAt   DATETIME2(0) NULL,
    FetchedAt    DATETIME2(0) NULL
);

CREATE TABLE dbo.RH_ComposicaoRemuneracao (
    Id                              BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SyncId                          UNIQUEIDENTIFIER NOT NULL,
    RowNum                          INT NOT NULL,
    CONTRATO                        NVARCHAR(80) NULL,
    TIPOCONTRATO                    NVARCHAR(40) NULL,
    VINCULOEMPREGATICIO             NVARCHAR(40) NULL,
    NOME                            NVARCHAR(250) NULL,
    CARGO                           NVARCHAR(200) NULL,
    SEXO                            NVARCHAR(5) NULL,
    NASCIMENTO                      DATE NULL,
    CPF                             NVARCHAR(20) NULL,
    UNIDADE                         NVARCHAR(40) NULL,
    CODIGOEMPRESA                   NVARCHAR(40) NULL,
    NOMEEMPRESA                     NVARCHAR(200) NULL,
    CODIGOESTABELECIMENTO           NVARCHAR(40) NULL,
    NOMEESTABELECIMENTO             NVARCHAR(200) NULL,
    CNPJ                            NVARCHAR(20) NULL,
    NOMECARGOGERENTE                NVARCHAR(200) NULL,
    NOMEGERENTE                     NVARCHAR(250) NULL,
    CODIGOCLASSIFICACAOCONTABIL     NVARCHAR(40) NULL,
    DESCRICAOCLASSIFICACAOCONTABIL  NVARCHAR(200) NULL,
    CODIGOCENTRODECUSTO             NVARCHAR(40) NULL,
    DESCRICAOCENTROCUSTO1           NVARCHAR(200) NULL,
    CODIGOSITUACAO                  NVARCHAR(20) NULL,
    FERIASNOMES                     NVARCHAR(5) NULL,
    DATAADMISSAO                    DATE NULL,
    MESESCASA                       INT NULL,
    MESESCARGO                      INT NULL,
    DATAULTTRANSFERENCIA            DATE NULL,
    DATAULTIMOREAJUSTE              DATE NULL,
    MOTIVOALTERACAOSALARIO          NVARCHAR(200) NULL,
    HORASCONTRATUAIS                DECIMAL(18,4) NULL,
    DATALANCAMENTO                  DATE NULL,
    SALARIO_CONTRATUAL_HIST         DECIMAL(18,4) NULL,
    SALARIO_CONTRATUAL_FOLHA        DECIMAL(18,4) NULL,
    DECIMO_TERCEIRO                 DECIMAL(18,4) NULL,
    FERIAS                          DECIMAL(18,4) NULL,
    INSS                            DECIMAL(18,4) NULL,
    GARANTIA_MINIMA                 DECIMAL(18,4) NULL,
    FGTS                            DECIMAL(18,4) NULL,
    AJUDA_DE_CUSTO                  DECIMAL(18,4) NULL,
    ADIC_TEMPO_CASA                 DECIMAL(18,4) NULL,
    INSALUBRIDADE                   DECIMAL(18,4) NULL,
    PERICULOSIDADE                  DECIMAL(18,4) NULL,
    HORA_EXTRA_50                   DECIMAL(18,4) NULL,
    HORA_EXTRA_60                   DECIMAL(18,4) NULL,
    HORA_EXTRA_100                  DECIMAL(18,4) NULL,
    REPOUSO_HE                      DECIMAL(18,4) NULL,
    HORA_EXTRA_M                    DECIMAL(18,4) NULL,
    ADICIONAL_NOTURNO               DECIMAL(18,4) NULL,
    ADICIONAL_NOTURNO_M             DECIMAL(18,4) NULL,
    COMISSAO                        DECIMAL(18,4) NULL,
    COMISSAO_M                      DECIMAL(18,4) NULL,
    REPOUSO_COMISSAO                DECIMAL(18,4) NULL,
    REPOUSO_COMISSAO_M              DECIMAL(18,4) NULL,
    PREMIACAO                       DECIMAL(18,4) NULL,
    PREMIACAO_M                     DECIMAL(18,4) NULL,
    BONIFICACAO                     DECIMAL(18,4) NULL,
    BONIFICACAO_M                   DECIMAL(18,4) NULL,
    META_DIRETORIA                  DECIMAL(18,4) NULL,
    META_DIRETORIA_M                DECIMAL(18,4) NULL,
    TREINAMENTO                     DECIMAL(18,4) NULL,
    TREINAMENTO_M                   DECIMAL(18,4) NULL,
    SALARIO_DOENCA_SOBRE_COMISSAO   DECIMAL(18,4) NULL,
    SALARIO_DOENCA_SOBRE_COMISSAO_M DECIMAL(18,4) NULL,
    ASS_MEDICA_COLABORADOR_EMPREGADO DECIMAL(18,4) NULL,
    ASS_ODONTOLOGICA                DECIMAL(18,4) NULL,
    ASS_ODONTOLOGICA_DEPENDENTES    DECIMAL(18,4) NULL,
    ALIMENTACAO                     DECIMAL(18,4) NULL,
    TRANSPORTE                      DECIMAL(18,4) NULL,
    AUXILIO_MOBILIDADE              DECIMAL(18,4) NULL,
    TOTAL_BRUTO_DESLIGAMENTO        DECIMAL(18,4) NULL,
    MULTA_FGTS                      DECIMAL(18,4) NULL,
    FGTS_RESCISAO                   DECIMAL(18,4) NULL,
    DATARESCISAO                    DATE NULL,
    CODIGOMOTIVORESCISAO            NVARCHAR(40) NULL,
    MOTIVORESCISAO                  NVARCHAR(200) NULL,
    CPF_LIDER                       NVARCHAR(20) NULL,
    CreatedAt                       DATETIME2(0) NOT NULL CONSTRAINT DF_RH_Comp_CreatedAt DEFAULT (SYSDATETIME())
);

CREATE INDEX IX_RH_Comp_Sync_Row
    ON dbo.RH_ComposicaoRemuneracao (SyncId, RowNum);
CREATE INDEX IX_RH_Comp_Sync_Contrato
    ON dbo.RH_ComposicaoRemuneracao (SyncId, CONTRATO);
CREATE INDEX IX_RH_Comp_Sync_Nome
    ON dbo.RH_ComposicaoRemuneracao (SyncId, NOME);
CREATE INDEX IX_RH_CompJob_Active
    ON dbo.RH_ComposicaoJob (IsActive, Status, FinishedAt DESC);
